spring.application.name=Platform

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/scheduling_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true

# Java 21 Virtual Threads
spring.threads.virtual.enabled=true